# Copyright (c) 2023-2026 Yaroslav Vasylenko (neuron7xLab)
# SPDX-License-Identifier: MIT
"""D-002G-P3 — Adversarial traps for the constant-payload adjudication.

Each trap is a SHOULD-FAIL attack that the eligibility ladder must
reject. Traps are deliberately minimal to keep python-fast-tests
under its 20-min budget; multi-seed sweeps are marked `slow`.

Trap rungs
----------
* R-T1: spuriously diverse node payload masking topology coupling.
* R-T2: same-shape topology mutation (matrix shape preserved but
  support pattern flipped).
* R-T3: identity-permutation label shuffle has no effect → must
  not be promoted to "ELIGIBLE because non-trivial".
* R-T4: missing provenance must NOT be silently absorbed.
* R-T5: salt collisions between sub-domain streams (must be
  detected or documented as accepted-distinct).
* R-T6: temporal-lag violation under injection-sequence permutation
  must trip CONTRACT_VIOLATION rather than ELIGIBLE.
* R-T7: block-semantics mutation under node permutation must trip
  TOPOLOGY_COUPLED.
* R-T8: claim-leakage trap — any test that emits the literal
  string "D-002G PASS" outside the forbidden-context list fails.
"""

from __future__ import annotations

import numpy as np

from research.systemic_risk.d002c_substrates import (
    SUBSTRATE_BY_ID,
    T_HORIZON,
    SubstrateInvalid,
    SubstrateRealization,
)
from research.systemic_risk.d002g_null_mechanisms import (
    M2_INJECTION_SEQUENCE_SALT,
    M2_NODE_PAYLOAD_SALT,
    M2_PLACEBO_SALT,
    deterministic_mix,
    verify_m2_injection_sequence_eligibility,
    verify_m2_node_payload_eligibility,
)

_LAMBDA = 0.4
_BASE_SEED = 42
_NULL_SEED = 12345


# ---- T1: fake payload diversity rejected --------------------------


class _FakeDiversityTrapSubstrate:
    """Substrate that synthesises ΔK row-sums with 2 distinct values
    via a permutation-coupled trick: rows are non-uniform BUT the
    diversity is generated by a per-row block label that IS the
    topology. The verifier must catch this as TOPOLOGY_COUPLED."""

    @property
    def id(self) -> str:
        return "synthetic_fake_diversity_trap"

    def realize(self, *, N: int, lambda_: float, seed: int) -> SubstrateRealization:
        # Block-labelled adjacency: first N/2 nodes have only intra-half
        # links, second N/2 has only intra-half. ΔK lifts each half by
        # a distinct magnitude → row-sums have 2 distinct values, but
        # PERMUTING node IDs across the halves would relocate the links
        # → topology hash mutates. Verifier must REFUSE.
        if N < 4:
            raise SubstrateInvalid("trap: N must be >= 4")
        half = N // 2
        A = np.zeros((N, N), dtype=np.float64)
        A[:half, :half] = 1.0
        A[half:, half:] = 1.0
        np.fill_diagonal(A, 0.0)
        lam = float(np.abs(np.linalg.eigvalsh(A)).max())
        K_c = float(N) / max(lam, 1e-12)
        K_static = A * K_c
        K_baseline = np.broadcast_to(K_static, (T_HORIZON, N, N)).astype(np.float64).copy()
        K_precursor = K_baseline.copy()
        if lambda_ > 0.0:
            lift = np.zeros((N, N), dtype=np.float64)
            lift[:half, :half] = 0.05 * lambda_ * K_c
            lift[half:, half:] = 0.10 * lambda_ * K_c
            np.fill_diagonal(lift, 0.0)
            for t in range(4, 6):
                K_precursor[t] = K_baseline[t] + lift
        _ = seed
        spec_b = float(
            np.mean([np.abs(np.linalg.eigvalsh(K_baseline[t])).max() for t in range(T_HORIZON)])
        ) / float(N)
        spec_p = float(
            np.mean([np.abs(np.linalg.eigvalsh(K_precursor[t])).max() for t in range(T_HORIZON)])
        ) / float(N)
        delta = float(np.linalg.norm(K_precursor - K_baseline))
        return SubstrateRealization(
            substrate_id=self.id,
            N=N,
            lambda_=lambda_,
            seed=seed,
            K_baseline=K_baseline,
            K_precursor=K_precursor,
            K_c=K_c,
            density=1.0,
            spectral_radius_over_N=spec_b,
            spectral_radius_over_N_precursor=spec_p,
            precursor_frobenius_delta=delta,
        )


def test_p3_trap_fake_payload_diversity_rejected() -> None:
    """Block-coupled fake diversity → TOPOLOGY_COUPLED, not ELIGIBLE."""
    sub = _FakeDiversityTrapSubstrate()
    v = verify_m2_node_payload_eligibility(
        sub, N=20, lambda_value=_LAMBDA, base_seed=_BASE_SEED, null_seed=_NULL_SEED
    )
    assert v.status == "INELIGIBLE_M2_NODE_PAYLOAD_TOPOLOGY_COUPLED", v.eligibility_reason


# ---- T2: same-shape topology mutation rejected --------------------


def test_p3_trap_same_shape_topology_mutation_rejected() -> None:
    """Topology hash is content-addressed; shape-preserving but
    mask-flipped delta is REJECTED."""
    from research.systemic_risk.d002g_null_mechanisms import _topology_hash

    N = 10
    a = np.zeros((N, N), dtype=np.float64)
    a[0, 1] = 1.0
    a[1, 0] = 1.0
    b = np.zeros((N, N), dtype=np.float64)
    b[0, 2] = 1.0
    b[2, 0] = 1.0
    # Same shape (N, N) but support mask differs → hashes differ.
    assert _topology_hash(a) != _topology_hash(b)


# ---- T3: label shuffle no-effect rejected -------------------------


def test_p3_trap_label_shuffle_no_effect_rejected() -> None:
    """Identity permutation (rng yields identity by chance) cannot
    inflate eligibility; the verifier's ladder is structural, not
    sampling-dependent. Test: when the ladder returns INELIGIBLE for
    one seed, it returns INELIGIBLE for ALL seeds we probe."""
    sub = SUBSTRATE_BY_ID["block_structured"]
    seen_statuses: set[str] = set()
    for ns in (12345, 999, 0, 7919, 314159, 271828, 1, 99999):
        v = verify_m2_node_payload_eligibility(
            sub, N=50, lambda_value=_LAMBDA, base_seed=_BASE_SEED, null_seed=ns
        )
        seen_statuses.add(v.status)
    expected = {"INELIGIBLE_M2_NODE_PAYLOAD_TOPOLOGY_COUPLED"}
    msg = f"verdict drifts across seeds (should be structural): {seen_statuses}"
    assert seen_statuses == expected, msg


# ---- T4: missing provenance rejected ------------------------------


class _RaisingSubstrate:
    @property
    def id(self) -> str:
        return "synthetic_raising"

    def realize(self, *, N: int, lambda_: float, seed: int) -> SubstrateRealization:
        raise SubstrateInvalid("simulated provenance failure for trap")


def test_p3_trap_missing_provenance_rejected() -> None:
    """Both verifiers route a raising substrate to INDETERMINATE."""
    sub = _RaisingSubstrate()
    v_n = verify_m2_node_payload_eligibility(
        sub, N=10, lambda_value=_LAMBDA, base_seed=_BASE_SEED, null_seed=_NULL_SEED
    )
    assert v_n.status == "INDETERMINATE_M2_NODE_PAYLOAD_PROVENANCE_MISSING"
    v_i = verify_m2_injection_sequence_eligibility(
        sub, N=10, lambda_value=_LAMBDA, base_seed=_BASE_SEED, null_seed=_NULL_SEED
    )
    assert v_i.status == "INDETERMINATE_M2_INJECTION_SEQUENCE_PROVENANCE_MISSING"


# ---- T5: seed-collision detected or documented --------------------


def test_p3_trap_seed_collision_detected_or_documented() -> None:
    """The three M2 sub-domain salts are distinct primes; the derived
    seeds for a fixed base_seed are pairwise distinct (collision-
    free under sha256 mixing)."""
    base = 42
    seeds = {
        "edge_weight": deterministic_mix(base, M2_PLACEBO_SALT),
        "node_payload": deterministic_mix(base, M2_NODE_PAYLOAD_SALT),
        "injection_sequence": deterministic_mix(base, M2_INJECTION_SEQUENCE_SALT),
    }
    assert len(set(seeds.values())) == 3, f"M2 sub-domain seed collision: {seeds}"


# ---- T6: temporal-lag violation rejected --------------------------


def test_p3_trap_temporal_lag_violation_rejected() -> None:
    """temporal_coupling CANNOT be admitted under injection_sequence —
    its lag-coupling contract is the substrate's identity."""
    sub = SUBSTRATE_BY_ID["temporal_coupling"]
    v = verify_m2_injection_sequence_eligibility(
        sub, N=50, lambda_value=_LAMBDA, base_seed=_BASE_SEED, null_seed=_NULL_SEED
    )
    assert v.status == "INELIGIBLE_M2_INJECTION_SEQUENCE_CONTRACT_VIOLATION"
    # Document the contract pointer
    assert "sinusoidal_envelope" in v.metadata["contract"]


# ---- T7: block-semantics mutation rejected ------------------------


def test_p3_trap_block_semantics_mutation_rejected() -> None:
    """block_structured: node-id permutation across blocks IS topology
    mutation, even though the K_baseline mask is fully-connected."""
    sub = SUBSTRATE_BY_ID["block_structured"]
    v = verify_m2_node_payload_eligibility(
        sub, N=50, lambda_value=_LAMBDA, base_seed=_BASE_SEED, null_seed=_NULL_SEED
    )
    assert v.status == "INELIGIBLE_M2_NODE_PAYLOAD_TOPOLOGY_COUPLED"
    # The verdict metadata pins both pre/post topology hashes so an
    # auditor can replicate the mutation.
    assert v.metadata["pre_delta_topology_hash"] != v.metadata["post_delta_topology_hash"]


# ---- T8: claim-leakage trap --------------------------------------


def test_p3_trap_claim_leakage_rejected() -> None:
    """Module surface MUST NOT carry a D-002G PASS claim literal."""
    from research.systemic_risk import d002g_null_mechanisms as mod

    # Inspect public surface
    for name in mod.__all__:
        obj = getattr(mod, name)
        s = repr(obj)
        # Banned strings: any active scientific PASS claim
        banned = (
            "D-002G validated",
            "scientific result confirmed",
            "M2 proves",
        )
        for phrase in banned:
            assert phrase not in s, f"banned claim in {name}: {phrase!r}"
