// Auto-generated by tools/schema/generate_event_types.py. DO NOT EDIT.

export enum FillLiquidity {
  MAKER = "MAKER",
  TAKER = "TAKER",
}

export enum FillStatus {
  PARTIAL = "PARTIAL",
  FILLED = "FILLED",
  CANCELLED = "CANCELLED",
}

export enum OrderSide {
  BUY = "BUY",
  SELL = "SELL",
}

export enum OrderType {
  MARKET = "MARKET",
  LIMIT = "LIMIT",
  STOP = "STOP",
  STOP_LIMIT = "STOP_LIMIT",
}

export enum SignalDirection {
  BUY = "BUY",
  SELL = "SELL",
  FLAT = "FLAT",
}

export enum TimeInForce {
  GTC = "GTC",
  DAY = "DAY",
  IOC = "IOC",
  FOK = "FOK",
}

export interface BarEvent {
  event_id: string;
  schema_version: string;
  symbol: string;
  timestamp: number;
  interval: string;
  open: number;
  high: number;
  low: number;
  close: number;
  volume: number;
  vwap?: number | null;
  trade_count?: number | null;
}

export interface FillEvent {
  event_id: string;
  schema_version: string;
  symbol: string;
  timestamp: number;
  order_id: string;
  fill_id: string;
  status: FillStatus;
  filled_qty: number;
  fill_price: number;
  fees?: number | null;
  liquidity?: FillLiquidity | null;
  metadata: Record<string, string>;
}

export interface OrderEvent {
  event_id: string;
  schema_version: string;
  symbol: string;
  timestamp: number;
  order_id: string;
  side: OrderSide;
  order_type: OrderType;
  quantity: number;
  price?: number | null;
  time_in_force?: TimeInForce | null;
  routing?: string | null;
  metadata: Record<string, string>;
}

export interface SignalEvent {
  event_id: string;
  schema_version: string;
  symbol: string;
  timestamp: number;
  signal_type: string;
  strength: number;
  direction: SignalDirection;
  ttl_seconds?: number | null;
  metadata: Record<string, string>;
}

export interface TickEvent {
  event_id: string;
  schema_version: string;
  symbol: string;
  timestamp: number;
  bid_price: number;
  ask_price: number;
  last_price?: number | null;
  volume?: number | null;
  microstructure?: TickMicrostructure | null;
}

export interface TickMicrostructure {
  bid_size?: number | null;
  ask_size?: number | null;
  trade_condition?: string | null;
}
