# Copyright (c) 2023-2026 Yaroslav Vasylenko (neuron7xLab)
# SPDX-License-Identifier: MIT
"""Strategy helpers exposed for CLI integrations."""

from .btc_intel import (
    DEFAULT_BTC_RULE_CONFIG,
    BTCMarketSnapshot,
    BTCRule,
    BTCRuleConfig,
    BTCRuleResult,
    BTCSignal,
    evaluate_btc_rules,
)
from .dsl import (
    ComponentParameters,
    ParameterField,
    StrategyComponentConfig,
    StrategyDSLLoader,
    StrategyMetadata,
    StrategyPipeline,
    StrategyPipelineDefinition,
    StrategyPresetRegistry,
    load_strategy_pipeline,
)
from .engine import (
    AcceptAllRiskPolicy,
    InvalidModeTransition,
    IOContract,
    RiskAdvice,
    RiskAdviceLevel,
    RiskAssessment,
    RiskPolicy,
    StrategyCancel,
    StrategyContext,
    StrategyEngine,
    StrategyEngineEvent,
    StrategyEngineMode,
    StrategyEventType,
    StrategyModule,
    StrategySignal,
)
from .fete import (
    FETE,
    AdvancedRegimeDetector,
    FETEConfig,
    FractalEMA,
    HurstExponentAnalyzer,
    MultiScaleRiskMonitor,
    PositionSizer,
    Regime,
    SigmaConfig,
    SigmaController,
    SimpleEMD,
    SpectralAnalyzer,
    binary_entropy,
)
from .fete_runtime import (
    BacktestReport,
    BinanceRESTFetcher,
    ExecutedTrade,
    FETEBacktestEngine,
    HistoricalCandle,
    PaperTradingAccount,
    RiskEvent,
    RiskGuard,
    YahooFinanceDataFetcher,
)
from .objectives import sharpe_ratio
from .signals import moving_average_signal, threshold_signal
from .trading import (
    HurstVPINStrategy,
    KuramotoStrategy,
    TradingStrategy,
    register_strategies,
)

__all__ = [
    "moving_average_signal",
    "threshold_signal",
    "sharpe_ratio",
    "TradingStrategy",
    "KuramotoStrategy",
    "HurstVPINStrategy",
    "register_strategies",
    "FETE",
    "FETEConfig",
    "Regime",
    "HurstExponentAnalyzer",
    "SpectralAnalyzer",
    "SimpleEMD",
    "AdvancedRegimeDetector",
    "SigmaController",
    "SigmaConfig",
    "PositionSizer",
    "MultiScaleRiskMonitor",
    "binary_entropy",
    "FractalEMA",
    "HistoricalCandle",
    "YahooFinanceDataFetcher",
    "BinanceRESTFetcher",
    "ExecutedTrade",
    "PaperTradingAccount",
    "RiskEvent",
    "RiskGuard",
    "BacktestReport",
    "FETEBacktestEngine",
    "StrategyPipelineDefinition",
    "StrategyPipeline",
    "StrategyDSLLoader",
    "StrategyComponentConfig",
    "StrategyMetadata",
    "ParameterField",
    "ComponentParameters",
    "StrategyPresetRegistry",
    "load_strategy_pipeline",
    "StrategyEngine",
    "StrategyEngineMode",
    "StrategyEngineEvent",
    "StrategyEventType",
    "StrategyModule",
    "StrategyContext",
    "StrategySignal",
    "StrategyCancel",
    "RiskAdvice",
    "RiskAdviceLevel",
    "RiskAssessment",
    "RiskPolicy",
    "AcceptAllRiskPolicy",
    "IOContract",
    "InvalidModeTransition",
    "BTCMarketSnapshot",
    "BTCRule",
    "BTCRuleConfig",
    "BTCRuleResult",
    "BTCSignal",
    "DEFAULT_BTC_RULE_CONFIG",
    "evaluate_btc_rules",
]
