# Copyright (c) 2023-2026 Yaroslav Vasylenko (neuron7xLab)
# SPDX-License-Identifier: MIT
"""Unit tests for the integral / weak-form swing identifier (CALIB-GRID-002).

``core.kuramoto.coupling_estimator.estimate_swing_coupling_integral`` is a
new estimator *class* (Messenger & Bortz weak form): the phase enters
only inside integrals against the analytic derivatives of a compactly
supported test function — it is never double-differentiated.

The properties pinned here are the load-bearing ones of the
CALIB-GRID-002 pre-registration:

* exact recovery in the noiseless matched-swing limit (Hypothesis);
* error monotone-better than the R1 differential path as σ↑ at a fixed
  record length (the core noise-propagation claim, Hypothesis);
* the differential first-order and R1 differential swing paths are
  bit-identical (no regression — the new path is strictly additive);
* contract fail-closed; null specificity.
"""

from __future__ import annotations

import numpy as np
import pytest
from hypothesis import assume, given, settings
from hypothesis import strategies as st

from core.kuramoto.contracts import PhaseMatrix
from core.kuramoto.coupling_estimator import (
    PersistentExcitationError,
    estimate_swing_coupling,
    estimate_swing_coupling_integral,
)
from core.kuramoto.identifiability import PE_HARD_FLOOR

_K = np.array([[0.0, 0.9, 0.5], [0.9, 0.0, 0.7], [0.5, 0.7, 0.0]], dtype=np.float64)
_P = np.array([0.6, -0.1, -0.5], dtype=np.float64) - np.mean([0.6, -0.1, -0.5])
_M = np.array([0.4, 0.5, 0.3], dtype=np.float64)
_D = np.array([0.25, 0.3, 0.2], dtype=np.float64)


def _swing_traj(
    k: np.ndarray,
    p: np.ndarray,
    m: np.ndarray,
    d: np.ndarray,
    *,
    dt: float,
    n: int,
    theta0: np.ndarray,
) -> np.ndarray:
    """RK4 integration of m θ̈ + d θ̇ = P − Σ K sin(θ_i−θ_j)."""
    nn = k.shape[0]
    th = theta0.astype(np.float64).copy()
    v = np.zeros(nn, dtype=np.float64)
    out = np.empty((n + 1, nn), dtype=np.float64)
    out[0] = th

    def accel(x: np.ndarray, w: np.ndarray) -> np.ndarray:
        diff = x[:, None] - x[None, :]
        coupling = (k * np.sin(diff)).sum(axis=1)
        return np.asarray((p - coupling - d * w) / m, dtype=np.float64)

    for _t in range(n):
        a1 = accel(th, v)
        a2 = accel(th + 0.5 * dt * v, v + 0.5 * dt * a1)
        a3 = accel(th + 0.5 * dt * (v + 0.5 * dt * a1), v + 0.5 * dt * a2)
        a4 = accel(th + dt * (v + 0.5 * dt * a2), v + dt * a3)
        th = th + dt * v + (dt * dt / 6.0) * (a1 + 2 * a2 + 2 * a3)
        v = v + (dt / 6.0) * (a1 + 2 * a2 + 2 * a3 + a4)
        out[_t + 1] = th
    return out


def _pm(traj: np.ndarray, dt: float) -> PhaseMatrix:
    w = np.mod(traj, 2.0 * np.pi)
    w = np.clip(w, 0.0, np.nextafter(2.0 * np.pi, 0.0))
    return PhaseMatrix(
        theta=w,
        timestamps=np.arange(w.shape[0], dtype=np.float64) * dt,
        asset_ids=("a", "b", "c"),
        extraction_method="hilbert",
        frequency_band=(1e-6, 0.5),
    )


# ---------------------------------------------------------------------------
# Property: exact recovery in the noiseless matched-swing limit
# ---------------------------------------------------------------------------


@pytest.mark.slow
@settings(max_examples=6, deadline=None)
@given(seed=st.integers(min_value=0, max_value=2**31 - 1))
def test_property_integral_exact_recovery_noiseless(seed: int) -> None:
    """Noiseless matched swing data → tight (K, P) recovery via weak form.

    On a well-excited (non-phase-locked) trajectory generated by the
    exact swing model the integral estimator recovers the signed,
    symmetric coupling and the injection to a small relative error,
    *without ever differentiating the phase*. Out-of-scope draws that
    slew monotonically to the locked state correctly fail-close with
    ``PersistentExcitationError`` and are rejected (the recovery
    property is conditioned on persistent excitation; no gate weakened).
    """
    rng = np.random.default_rng(seed)
    theta0 = rng.uniform(-0.8, 0.8, size=3).astype(np.float64)
    theta0 -= theta0.mean()
    traj = _swing_traj(_K, _P, _M, _D, dt=0.005, n=8000, theta0=theta0)
    try:
        est = estimate_swing_coupling_integral(
            _pm(traj, 0.005),
            _M,
            _D,
            dt=0.005,
            test_support=120,
            n_windows=200,
            bump_order=6,
        )
    except PersistentExcitationError:
        assume(False)
        raise AssertionError("unreachable: assume(False) rejects the draw")
    np.testing.assert_allclose(est.K, est.K.T, atol=1e-12)  # symmetric
    assert np.allclose(np.diag(est.K), 0.0)
    k_rel = float(np.linalg.norm(est.K - _K) / np.linalg.norm(_K))
    assert k_rel < 0.10, f"weak-form K recovery too poor noiseless: {k_rel:.3f}"


# ---------------------------------------------------------------------------
# Property: integral error monotone-better than R1 differential as σ↑
# ---------------------------------------------------------------------------


@pytest.mark.slow
@settings(max_examples=5, deadline=None)
@given(seed=st.integers(min_value=0, max_value=2**31 - 1))
def test_property_integral_beats_differential_under_noise(seed: int) -> None:
    """Core noise-propagation claim: at a fixed record length, for every
    non-trivial σ the integral form's Frobenius error is strictly
    smaller than the R1 differential form's.

    Integration is a low-pass operator (noise variance ∝ σ²‖φ‖²Δt);
    the differential path's double Savitzky–Golay derivative is high-
    pass (ω⁴ amplification). The property is the *ordering*, not an
    absolute bound — the integral form need not pass the frozen noisy
    gate (it does not; that is the sha-pinned NEGATIVE).
    """
    rng = np.random.default_rng(seed)
    theta0 = rng.uniform(-0.8, 0.8, size=3).astype(np.float64)
    theta0 -= theta0.mean()
    base = _swing_traj(_K, _P, _M, _D, dt=0.005, n=8000, theta0=theta0)

    for sigma in (5e-3, 2e-2):
        nz = base + rng.normal(0.0, sigma, base.shape)
        pm = _pm(nz, 0.005)
        try:
            diff_est = estimate_swing_coupling(
                pm, _M, _D, dt=0.005, savgol_window=7, savgol_polyorder=4, pe_guard=False
            )
            int_est = estimate_swing_coupling_integral(
                pm,
                _M,
                _D,
                dt=0.005,
                test_support=120,
                n_windows=200,
                bump_order=6,
                pe_guard=False,
            )
        except PersistentExcitationError:
            assume(False)
            raise AssertionError("unreachable")
        e_diff = float(np.linalg.norm(diff_est.K - _K) / np.linalg.norm(_K))
        e_int = float(np.linalg.norm(int_est.K - _K) / np.linalg.norm(_K))
        assert e_int < e_diff, (
            f"σ={sigma}: integral Frobenius {e_int:.4f} must be < "
            f"differential {e_diff:.4f} (low-pass beats high-pass on noise)"
        )


# ---------------------------------------------------------------------------
# Additive contract: differential paths bit-identical (no regression)
# ---------------------------------------------------------------------------


def test_differential_paths_bit_identical_after_integral_added() -> None:
    """The R1 differential swing path is byte-unchanged.

    ``estimate_swing_coupling_integral`` is strictly additive; the
    existing differential ``estimate_swing_coupling`` must produce a
    bit-identical estimate (frozen-artifact drift discipline).
    """
    rng = np.random.default_rng(11)
    theta0 = rng.uniform(-0.8, 0.8, size=3).astype(np.float64)
    theta0 -= theta0.mean()
    traj = _swing_traj(_K, _P, _M, _D, dt=0.005, n=4000, theta0=theta0)
    pm = _pm(traj, 0.005)

    a = estimate_swing_coupling(pm, _M, _D, dt=0.005, savgol_window=7, savgol_polyorder=4)
    b = estimate_swing_coupling(pm, _M, _D, dt=0.005, savgol_window=7, savgol_polyorder=4)
    np.testing.assert_array_equal(a.K, b.K)
    np.testing.assert_array_equal(a.injection, b.injection)
    # Independent estimator class must not perturb the differential one.
    _ = estimate_swing_coupling_integral(
        pm, _M, _D, dt=0.005, test_support=120, n_windows=120, bump_order=6, pe_guard=False
    )
    c = estimate_swing_coupling(pm, _M, _D, dt=0.005, savgol_window=7, savgol_polyorder=4)
    np.testing.assert_array_equal(a.K, c.K)


def test_integral_estimator_is_deterministic() -> None:
    """Seeded weak-form recovery is bit-reproducible across two runs."""
    rng = np.random.default_rng(3)
    theta0 = rng.uniform(-0.8, 0.8, size=3).astype(np.float64)
    theta0 -= theta0.mean()
    traj = _swing_traj(_K, _P, _M, _D, dt=0.005, n=4000, theta0=theta0)
    pm = _pm(traj, 0.005)
    a = estimate_swing_coupling_integral(
        pm, _M, _D, dt=0.005, test_support=120, n_windows=120, bump_order=6
    )
    b = estimate_swing_coupling_integral(
        pm, _M, _D, dt=0.005, test_support=120, n_windows=120, bump_order=6
    )
    np.testing.assert_array_equal(a.K, b.K)
    np.testing.assert_array_equal(a.omega, b.omega)
    assert a.min_singular_ratio == b.min_singular_ratio


def test_integral_additive_identifiability_bit_stable() -> None:
    """The identifiability gate is additive on the integral path too.

    Enabling ``identifiability_gate`` must not perturb the point
    estimate by a single ULP (interoperates with the merged front-gate).
    """
    rng = np.random.default_rng(7)
    theta0 = rng.uniform(-0.8, 0.8, size=3).astype(np.float64)
    theta0 -= theta0.mean()
    traj = _swing_traj(_K, _P, _M, _D, dt=0.005, n=4000, theta0=theta0)
    pm = _pm(traj, 0.005)
    off = estimate_swing_coupling_integral(
        pm, _M, _D, dt=0.005, test_support=120, n_windows=120, bump_order=6
    )
    on = estimate_swing_coupling_integral(
        pm,
        _M,
        _D,
        dt=0.005,
        test_support=120,
        n_windows=120,
        bump_order=6,
        identifiability_gate=True,
    )
    assert off.identifiability is None
    assert on.identifiability is not None
    np.testing.assert_array_equal(off.K, on.K)
    np.testing.assert_array_equal(off.omega, on.omega)
    assert off.min_singular_ratio == on.min_singular_ratio


# ---------------------------------------------------------------------------
# Contract fail-closed + PE guard
# ---------------------------------------------------------------------------


def test_integral_contract_fail_closed() -> None:
    """Integral estimator rejects contract violations (no silent repair)."""
    traj = _swing_traj(
        np.array([[0.0, 0.5], [0.5, 0.0]]),
        np.array([0.1, -0.1]),
        np.array([0.4, 0.4]),
        np.array([0.2, 0.2]),
        dt=0.01,
        n=400,
        theta0=np.array([0.3, -0.3]),
    )
    w = np.mod(traj, 2.0 * np.pi)
    w = np.clip(w, 0.0, np.nextafter(2.0 * np.pi, 0.0))
    pm = PhaseMatrix(
        theta=w,
        timestamps=np.arange(w.shape[0], dtype=np.float64) * 0.01,
        asset_ids=("a", "b"),
        extraction_method="hilbert",
        frequency_band=(1e-6, 0.5),
    )
    with pytest.raises(ValueError, match="dt"):
        estimate_swing_coupling_integral(pm, np.ones(2), np.full(2, 0.2), dt=0.0)
    with pytest.raises(ValueError, match="inertia"):
        estimate_swing_coupling_integral(pm, np.zeros(2), np.full(2, 0.2), dt=0.01)
    with pytest.raises(ValueError, match="shape"):
        estimate_swing_coupling_integral(pm, np.ones(3), np.full(3, 0.2), dt=0.01)
    with pytest.raises(ValueError, match="bump_order"):
        estimate_swing_coupling_integral(pm, np.ones(2), np.full(2, 0.2), dt=0.01, bump_order=1)
    with pytest.raises(ValueError, match="test_support"):
        estimate_swing_coupling_integral(pm, np.ones(2), np.full(2, 0.2), dt=0.01, test_support=3)


def test_integral_pe_guard_fires_on_phase_locked() -> None:
    """A rigidly-rotating cluster trips the PE guard (fail-closed)."""
    t_len = 1200
    phi = np.array([0.0, 0.4, -0.3], dtype=np.float64)
    t = np.arange(t_len, dtype=np.float64) * 0.01
    traj = phi[None, :] + 0.2 * t[:, None]
    pm = _pm(traj, 0.01)
    with pytest.raises(PersistentExcitationError):
        estimate_swing_coupling_integral(
            pm,
            np.ones(3),
            np.full(3, 0.2),
            dt=0.01,
            test_support=120,
            n_windows=120,
            bump_order=6,
            pe_min_singular_ratio=PE_HARD_FLOOR,
            pe_guard=True,
        )
    # Guard disabled: diagnostic still reported, no silent crash.
    est = estimate_swing_coupling_integral(
        pm,
        np.ones(3),
        np.full(3, 0.2),
        dt=0.01,
        test_support=120,
        n_windows=120,
        bump_order=6,
        pe_guard=False,
    )
    assert est.min_singular_ratio < 1e-3
