apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: geosync-production

resources:
  - ../../namespaces/production
  - priorityclass.yaml
  - ../../addons/backups
  - ../../addons/logging
  - ../../base

images:
  - name: ghcr.io/neuron7xLab/GeoSync
    newTag: stable

patches:
  - path: patches/deployment-high-availability.yaml
  - path: patches/hpa-high-throughput.yaml
