# Copyright (c) 2023-2026 Yaroslav Vasylenko (neuron7xLab)
# SPDX-License-Identifier: MIT
"""Deterministic markdown renderer for the D-002J verdict lineage map.

CLI
---

    python -m tools.governance.render_lineage [--out PATH]

Reads every capsule JSON under ``artifacts/governance/verdicts/`` via
:mod:`tools.governance.verdict_dag`, then writes a markdown document
to ``docs/research/D002J_LINEAGE_MAP.md`` (or ``--out``).

The output is **byte-identical** across runs when the input DAG is
unchanged: the generator timestamp is omitted from the document body
(an "anchor" placeholder is used instead); table rows are sorted by
topological order with alpha-ordered ties; locked governance SHAs
appear sorted by file path; the forbidden-claims aggregate is the
literal tuple from :data:`verdict_dag._FORBIDDEN_CLAIMS_AGGREGATE`.

The reason for timestamp omission is the idempotence invariant
exercised by ``test_lineage_map_md_renders_deterministically``: the
test calls :func:`render_lineage` twice in a fresh tmp directory and
asserts the produced bytes match. A wall-clock timestamp would break
that contract immediately.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Final

from tools.governance.verdict_dag import (
    _FORBIDDEN_CLAIMS_AGGREGATE,
    LOCKED_GOVERNANCE_SHAS,
    REPO_ROOT,
    VERDICTS_DIR_REL,
    VerdictCapsule,
    detect_orphans,
    load_dag,
    topological_order,
)

DEFAULT_OUTPUT_REL: Final[str] = "docs/research/D002J_LINEAGE_MAP.md"
"""Default destination for the rendered markdown lineage map.

The filename is retained for backward compatibility, but the document
now spans the connected D-002J / D-002K lineages (D-002K-P0's parent is
``D002J-P7``: D-002K exists *because* D-002J-P7 refused). A single
combined map is preferred over a split one precisely because the
lineage is connected — splitting would visually hide the honest
``D002J-P7 -> D002K-P0`` fresh-restart descent.
"""


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _short_sha(full: str) -> str:
    """Return the canonical 7-char short form of a 40-char merge sha."""
    if len(full) < 7:
        return full
    return full[:7]


def _format_list(items: tuple[str, ...] | list[str]) -> str:
    """Return a comma-separated rendering of *items* for table cells."""
    if not items:
        return "—"
    return ", ".join(items)


# ---------------------------------------------------------------------------
# Section renderers
# ---------------------------------------------------------------------------


def _render_header() -> list[str]:
    """Return §0 header lines (timestamp-free for idempotence)."""
    return [
        "<!-- AUTO-GENERATED by tools.governance.render_lineage. DO NOT EDIT. -->",
        "<!-- Re-run: `python -m tools.governance.render_lineage` -->",
        "",
        "# D-002J / D-002K Verdict DAG — Lineage Map",
        "",
        "Generator: `tools.governance.render_lineage`. ",
        "Source: `artifacts/governance/verdicts/d002[jk]_p*_verdict_v1.json` ",
        "(schema `D002J-VERDICT-CAPSULE-v1`).",
        "Spans the connected D-002J / D-002K lineages: `D002K-P0`'s parent ",
        "is `D002J-P7` — D-002K exists *because* D-002J-P7 terminally ",
        "refused (no rescue).",
        "Self-verdict node: `D002J-P2.5` (merge sha resolved at land time).",
        "",
    ]


def _render_lineage_chain(order: list[str], dag: dict[str, VerdictCapsule]) -> list[str]:
    """Return §1 lineage chain (mermaid graph + ASCII fallback)."""
    lines: list[str] = ["## §1 Lineage chain", "", "```mermaid", "graph LR"]
    for node_id in order:
        c = dag[node_id]
        label = f"{node_id}<br/>{c.status}"
        # Use literal node id as mermaid node anchor.
        lines.append(f"    {node_id}[{label}]")
    for node_id in order:
        c = dag[node_id]
        for parent in c.parent_nodes:
            lines.append(f"    {parent} --> {node_id}")
    lines.append("```")
    lines.append("")
    lines.append("ASCII fallback:")
    lines.append("")
    lines.append("```")
    lines.append(" -> ".join(order))
    lines.append("```")
    lines.append("")
    return lines


def _render_node_table(order: list[str], dag: dict[str, VerdictCapsule]) -> list[str]:
    """Return §2 per-node table."""
    header = (
        "| node_id | phase | PR | merge_sha (short) | decision | status | parent | allowed_next |"
    )
    sep = "|---------|-------|----|-------------------|----------|--------|--------|--------------|"
    lines: list[str] = [
        "## §2 Per-node table",
        "",
        header,
        sep,
    ]
    for node_id in order:
        c = dag[node_id]
        parent = _format_list(c.parent_nodes)
        next_nodes = _format_list(c.allowed_next_nodes)
        row = (
            f"| `{node_id}` | {c.phase} | #{c.pr_number} | `{_short_sha(c.merge_sha)}` | "
            f"`{c.decision}` | `{c.status}` | {parent} | {next_nodes} |"
        )
        lines.append(row)
    lines.append("")
    return lines


def _render_rejected(order: list[str], dag: dict[str, VerdictCapsule]) -> list[str]:
    """Return §3 retained rejected nodes section with repair pointers."""
    rejected = [n for n in order if dag[n].status in {"TERMINAL_REJECTED", "TERMINAL_REFUSED"}]
    lines: list[str] = [
        "## §3 Retained rejected nodes",
        "",
    ]
    if not rejected:
        lines.append("None.")
        lines.append("")
        return lines
    lines.append(
        "These nodes shipped a TERMINAL_REJECTED or TERMINAL_REFUSED verdict and "
        "are retained verbatim as truthful negative artifacts. Subsequent phases "
        "repair the underlying defect without rewriting history."
    )
    lines.append("")
    # Build repair map: for each rejected node, find children whose
    # parent_nodes include it.
    repair_map: dict[str, list[str]] = {n: [] for n in rejected}
    for node_id in order:
        c = dag[node_id]
        for parent in c.parent_nodes:
            if parent in repair_map:
                repair_map[parent].append(node_id)
    for r in rejected:
        c = dag[r]
        repairs = repair_map.get(r) or []
        repair_str = ", ".join(f"`{x}`" for x in repairs) if repairs else "(none)"
        lines.append(f"### `{r}` — `{c.decision}`")
        lines.append("")
        lines.append(f"- PR #{c.pr_number} at `{c.merge_sha}`")
        lines.append(f"- Repaired by: {repair_str}")
        lines.append("- Failure retention:")
        lines.append("")
        lines.append(f"  > {c.failure_retention or '(none recorded)'}")
        lines.append("")
    return lines


def _render_next_legal(order: list[str], dag: dict[str, VerdictCapsule]) -> list[str]:
    """Return §4 next legal nodes from main HEAD (leaf union)."""
    has_successor: set[str] = set()
    for c in dag.values():
        for parent in c.parent_nodes:
            has_successor.add(parent)
    leaves = [n for n in order if n not in has_successor]
    next_legal: set[str] = set()
    for leaf in leaves:
        next_legal.update(dag[leaf].allowed_next_nodes)
    lines: list[str] = [
        "## §4 Next legal nodes from main HEAD",
        "",
    ]
    if not next_legal:
        lines.append("No further nodes declared. The DAG is sealed.")
    else:
        for nid in sorted(next_legal):
            lines.append(f"- `{nid}`")
    lines.append("")
    return lines


def _render_forbidden() -> list[str]:
    """Return §5 forbidden claims aggregate."""
    lines: list[str] = [
        "## §5 Forbidden claims aggregate",
        "",
        "Every node in the DAG carries a `claim_boundary`. The union of forbidden",
        "claims is enforced fail-closed across the entire D-002J lineage. No PR",
        "may state, imply, or rely on any of the following:",
        "",
    ]
    for claim in _FORBIDDEN_CLAIMS_AGGREGATE:
        lines.append(f"- {claim}")
    lines.append("")
    return lines


def _render_locked_shas() -> list[str]:
    """Return §6 locked governance shas table."""
    lines: list[str] = [
        "## §6 Locked governance SHAs (byte-exact)",
        "",
        "These six anchors are protected by acceptor `forbidden_paths` and by",
        "the byte-exact sha256 set in `tools.governance.verdict_dag.LOCKED_GOVERNANCE_SHAS`.",
        "",
        "| path | sha256 |",
        "|------|--------|",
    ]
    for path in sorted(LOCKED_GOVERNANCE_SHAS):
        sha = LOCKED_GOVERNANCE_SHAS[path]
        lines.append(f"| `{path}` | `{sha}` |")
    lines.append("")
    return lines


# ---------------------------------------------------------------------------
# Top-level renderer
# ---------------------------------------------------------------------------


def render_lineage(verdicts_dir: Path) -> str:
    """Return the rendered markdown document as a single string.

    Pure of side effects; the caller chooses where to persist. The
    output is byte-identical across runs when the input DAG is
    unchanged (deterministic header, sorted tables, no timestamp).
    """
    dag = load_dag(verdicts_dir)
    order = topological_order(dag)
    orphans = detect_orphans(dag)
    if orphans:
        msg = f"render_lineage refuses to render a DAG with orphans: {orphans}"
        raise ValueError(msg)
    lines: list[str] = []
    lines.extend(_render_header())
    lines.extend(_render_lineage_chain(order, dag))
    lines.extend(_render_node_table(order, dag))
    lines.extend(_render_rejected(order, dag))
    lines.extend(_render_next_legal(order, dag))
    lines.extend(_render_forbidden())
    lines.extend(_render_locked_shas())
    return "\n".join(lines) + "\n" if not lines[-1].endswith("\n") else "\n".join(lines)


def write_lineage(verdicts_dir: Path, out_path: Path) -> Path:
    """Render and persist the markdown document to *out_path*.

    Creates parent directories if missing. Returns *out_path* for
    convenience so callers can chain into a check.
    """
    body = render_lineage(verdicts_dir)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(body, encoding="utf-8")
    return out_path


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def main(argv: list[str] | None = None) -> int:
    """Module-level CLI entry point. Returns a Unix exit code."""
    parser = argparse.ArgumentParser(
        prog="python -m tools.governance.render_lineage",
        description=(
            "Render the D-002J verdict-DAG lineage markdown map from the "
            "on-disk capsule JSONs. Deterministic: same DAG => same bytes."
        ),
    )
    parser.add_argument(
        "--verdicts-dir",
        type=Path,
        default=REPO_ROOT / VERDICTS_DIR_REL,
        help="directory containing the per-phase capsule JSONs",
    )
    parser.add_argument(
        "--out",
        type=Path,
        default=REPO_ROOT / DEFAULT_OUTPUT_REL,
        help="destination markdown file",
    )
    args = parser.parse_args(argv)
    try:
        out_path = write_lineage(args.verdicts_dir, args.out)
    except Exception as exc:
        sys.stderr.write(f"render_lineage FAILED: {exc}\n")
        return 2
    sys.stdout.write(f"render_lineage OK: wrote {out_path}\n")
    return 0


if __name__ == "__main__":  # pragma: no cover - thin CLI shim
    raise SystemExit(main())
